// Centralized Portuguese product copy. Niche-specific content is versioned in data/niches.ts.
export const ui = {
  "1": "1",
  "2": "2",
  "3": "3",
  quem_cuida_desta_pessoa: "Quem cuida desta pessoa?",
  responsavel_pela_pessoa: "Responsável pela pessoa",
  sem_responsavel: "Sem responsável",
  este_convite_expirou_foi_usado_ou_pertence_a_outro_e_ma:
    "Este convite expirou, foi usado ou pertence a outro e-mail. Peça um novo link ao dono do negócio.",
  atraction: "ION",
  confira_sua_conexao_e_tente_novamente:
    "Confira sua conexão e tente novamente.",
  nao_foi_possivel_criar_a_conta_use_uma_senha_com_pelo_m:
    "Não foi possível criar a conta. Use uma senha com pelo menos 8 caracteres ou tente entrar.",
  e_mail_ou_senha_nao_conferem_revise_e_tente_novamente:
    "E-mail ou senha não conferem. Revise e tente novamente.",
  nao_foi_possivel_criar_seu_espaco_tente_novamente:
    "Não foi possível criar seu espaço. Tente novamente.",
  nao_conseguimos_conectar_confira_sua_internet_e_tente_n:
    "Não conseguimos conectar. Confira sua internet e tente novamente.",
  seu_negocio_comeca_aqui: "Seu negócio começa aqui",
  crie_seu_espaco: "Crie seu espaço",
  que_bom_ter_voce_por_aqui: "Que bom ter você por aqui",
  seus_clientes_e_sua_equipe_no_mesmo_lugar:
    "Seus clientes e sua equipe, no mesmo lugar.",
  e_mail: "E-mail",
  senha: "Senha",
  criar_minha_conta: "Criar minha conta",
  entrar: "Entrar",
  ja_tenho_uma_conta: "Já tenho uma conta",
  primeira_vez_criar_conta_gratuita: "Primeira vez? Criar conta gratuita",
  confira_seu_e_mail: "Confira seu e-mail",
  abra_o_link_de_confirmacao_e_volte_para_entrar_na_sua_c:
    "Abra o link de confirmação e volte para entrar na sua conta.",
  voltar_para_entrar: "Voltar para entrar",
  nome_do_seu_negocio: "Nome do seu negócio",
  qual_e_o_seu_negocio: "Qual é o seu negócio?",
  quantas_pessoas_atendem: "Quantas pessoas atendem?",
  so_eu: "Só eu",
  "2_a_5_pessoas": "2 a 5 pessoas",
  "6_a_20_pessoas": "6 a 20 pessoas",
  de_onde_vem_os_clientes: "De onde vêm os clientes?",
  instagram: "Instagram",
  indicacao: "Indicação",
  whatsapp: "WhatsApp",
  passagem_na_rua: "Passagem na rua",
  seu_principal_objetivo: "Seu principal objetivo",
  nao_esquecer_de_ninguem: "Não esquecer de ninguém",
  fechar_mais_negocios: "Fechar mais negócios",
  fazer_clientes_voltarem: "Fazer clientes voltarem",
  abrir_meu_espaco: "Abrir meu espaço",
  preparando_uma_boa_conversa: "Preparando uma boa conversa…",
  esta_pagina_esta_descansando: "Esta página está descansando.",
  peca_um_novo_link_ao_negocio_com_quem_voce_quer_convers:
    "Peça um novo link ao negócio com quem você quer conversar.",
  o_primeiro_passo_esta_dado: "O primeiro passo está dado!",
  recebeu_seu_interesse_aguarde_um_contato_pelo_telefone_:
    "recebeu seu interesse. Aguarde um contato pelo telefone informado.",
  deixe_seu_nome_e_telefone_vamos_adorar_conhecer_voce:
    "Deixe seu nome e telefone. Vamos adorar conhecer você.",
  nao_foi_possivel_enviar_confira_o_telefone_com_ddd_e_te:
    "Não foi possível enviar. Confira o telefone com DDD e tente novamente em alguns minutos.",
  seu_nome: "Seu nome",
  seu_telefone: "Seu telefone",
  "11_99999_9999": "(11) 99999-9999",
  autorizo: "Autorizo ",
  a_entrar_em_contato_pelo_telefone_informado_sobre_meu_i:
    "a entrar em contato pelo telefone informado sobre meu interesse. Posso pedir para não receber mais mensagens a qualquer momento.",
  quero_saber_mais: "Quero saber mais",
  seus_dados_serao_disponibilizados_apenas_a_este_negocio:
    "Seus dados serão disponibilizados apenas a este negócio para responder ao seu pedido.",
  feito_com_no_atraction: "feito com ♡ no ION",
  cadastro: "Cadastro",
  editar_pessoa: "Editar pessoa",
  vamos_conhecer_alguem: "Vamos conhecer alguém?",
  so_precisamos_de_nome_e_telefone_o_resto_pode_ficar_par:
    "Só precisamos de nome e telefone. O resto pode ficar para depois.",
  nome: "Nome",
  telefone_com_ddd: "Telefone com DDD",
  e_mail_2: "E-mail ",
  opcional: "opcional",
  como_chegou: "Como chegou?",
  site: "Site",
  planilha: "Planilha",
  pagina: "Página",
  etiquetas: "Etiquetas ",
  separe_por_virgula: "separe por vírgula",
  anotacoes: "Anotações",
  autorizou_receber_mensagens_pelo_whatsapp:
    "Autorizou receber mensagens pelo WhatsApp",
  como_a_autorizacao_foi_recebida: "Como a autorização foi recebida?",
  ex_formulario_preenchido_em_19_09: "Ex.: formulário preenchido em 19/09",
  cancelar: "Cancelar",
  salvar_pessoa: "Salvar pessoa",
  cuidar_deste_negocio: "Cuidar deste negócio",
  uma_nova_oportunidade: "Uma nova oportunidade",
  pessoa: "Pessoa",
  escolha_uma_pessoa: "Escolha uma pessoa",
  o_que_voce_esta_oferecendo: "O que você está oferecendo?",
  valor_em_reais: "Valor em reais",
  em_que_momento_esta: "Em que momento está?",
  nao_foi_desta_vez: "Não foi desta vez",
  o_que_aconteceu: "O que aconteceu?",
  salvar_negocio: "Salvar negócio",
  tire_da_cabeca_deixe_com_a_gente: "Tire da cabeça. Deixe com a gente.",
  o_que_precisa_fazer: "O que precisa fazer?",
  ex_confirmar_a_avaliacao_da_mariana: "Ex.: confirmar a avaliação da Mariana",
  quando: "Quando?",
  sem_pessoa_vinculada: "Sem pessoa vinculada",
  tipo: "Tipo",
  tarefa: "Tarefa",
  compromisso: "Compromisso",
  guardar_na_agenda: "Guardar na agenda",
  suas_pessoas_todas_aqui: "Suas pessoas, todas aqui",
  importe_um_arquivo_csv_da_sua_planilha_com_as_colunas:
    "Importe um arquivo CSV da sua planilha, com as colunas ",
  nome_2: "nome",
  e: "e ",
  telefone: "telefone",
  e_mail_e_origem_sao_opcionais: ". E-mail e origem são opcionais.",
  escolher_planilha_csv: "Escolher planilha CSV",
  ate_10_000_pessoas_maximo_de_5_mb: "Até 10.000 pessoas · máximo de 5 MB",
  escolha_um_arquivo_de_ate_5_mb: "Escolha um arquivo de até 5 MB.",
  nome_telefone_email_origem_maria_exemplo_11999999999_in:
    "nome,telefone,email,origem\nMaria Exemplo,11999999999,,Indicação",
  baixar_planilha_de_exemplo: "Baixar planilha de exemplo",
  pessoas_prontas_para_importar: "pessoas prontas para importar · ",
  avisos: "avisos",
  a_importacao_nao_registra_autorizacao_de_envio_registre:
    "A importação não registra autorização de envio. Registre a autorização de cada pessoa antes de enviar mensagens.",
  importar: "Importar ",
  pessoas: "pessoas",
  meu_lembrete: "Meu lembrete",
  um_ajudante_do_seu_jeito: "Um ajudante do seu jeito",
  nome_do_robo: "Nome do robô",
  quando_acontecer: "Quando acontecer",
  uma_pessoa_nova_chegar: "Uma pessoa nova chegar",
  um_negocio_ficar_parado: "Um negócio ficar parado",
  esperar_quantas_horas: "Esperar quantas horas?",
  fazer_isto: "Fazer isto",
  criar_uma_tarefa_de_retorno: "Criar uma tarefa de retorno",
  previa: "Prévia: ",
  quando_um_negocio_ficar_parado: "quando um negócio ficar parado",
  criar_a_tarefa: ", criar a tarefa “",
  apos: "” após ",
  h_nenhuma_mensagem_sera_enviada: "h. Nenhuma mensagem será enviada.",
  o_robo_e_salvo_desligado_voce_decide_quando_ativar:
    "O robô é salvo desligado. Você decide quando ativar.",
  salvar_robo: "Salvar robô",
  dono: "Dono",
  gerente: "Gerente",
  atendente: "Atendente",
  somente_leitura: "Somente leitura",
  sua_equipe_mais_proxima: "Sua equipe, mais próxima",
  convide_quem_cuida_dos_clientes_com_voce_ate_10_pessoas:
    "Convide quem cuida dos clientes com você. Até 10 pessoas por negócio.",
  entre_em_uma_conta_real_para_convidar_sua_equipe:
    "Entre em uma conta real para convidar sua equipe.",
  convidar_uma_pessoa: "Convidar uma pessoa",
  crescer_fica_melhor_em_equipe: "Crescer fica melhor em equipe",
  nao_foi_possivel_preparar_o_convite_tente_novamente:
    "Não foi possível preparar o convite. Tente novamente.",
  e_mail_da_pessoa: "E-mail da pessoa",
  o_que_ela_pode_fazer: "O que ela pode fazer?",
  atendente_cuidar_das_pessoas_atribuidas:
    "Atendente — cuidar das pessoas atribuídas",
  gerente_cuidar_da_operacao_e_dos_resultados:
    "Gerente — cuidar da operação e dos resultados",
  somente_leitura_consultar_dados_e_resultados:
    "Somente leitura — consultar dados e resultados",
  o_convite_vale_por_7_dias_e_so_funciona_com_esse_e_mail:
    "O convite vale por 7 dias e só funciona com esse e-mail. Gerentes precisam de verificação em dois fatores.",
  criar_link_de_convite: "Criar link de convite",
  convite_preparado_envie_o_link_a_pessoa_nenhum_e_mail_f:
    "Convite preparado! Envie o link à pessoa. Nenhum e-mail foi enviado automaticamente.",
  link_do_convite: "Link do convite",
  convite_copiado: "Convite copiado.",
  selecione_o_link_para_copiar: "Selecione o link para copiar.",
  copiar_convite: "Copiar convite",
  tudo_em_dia_por_aqui: "Tudo em dia por aqui",
  sua_proxima_oportunidade_comeca_com_uma_conversa:
    "Sua próxima oportunidade começa com uma conversa.",
  fechar: "Fechar",
  todas: "Todas",
  nao_conseguimos_exportar_confira_sua_conexao_e_tente_no:
    "Não conseguimos exportar. Confira sua conexão e tente novamente.",
  planilha_exportada_guarde_em_um_lugar_seguro:
    "Planilha exportada. Guarde em um lugar seguro.",
  fechar_navegacao: "Fechar navegação",
  atraction_2: "ION",
  text: "®",
  seu_espaco: "SEU ESPAÇO",
  novo: "NOVO",
  um_passo_de_cada_vez: "Um passo de cada vez.",
  seu_negocio_pode_ir_longe: "Seu negócio pode ir longe.",
  a_gente_vai_junto: "A gente vai junto.",
  conhecer_o_atraction: "Conhecer o ION",
  voce_aqui: "Você aqui",
  seu_espaco_de_teste: "Seu espaço de teste",
  explore_a_vontade: "Explore à vontade",
  conta_protegida: "Conta protegida",
  abrir_navegacao: "Abrir navegação",
  meu_espaco: "Meu espaço",
  lixeira: "Lixeira",
  configuracoes: "Configurações",
  buscar_no_seu_espaco: "Buscar no seu espaço",
  k: "⌘ K",
  ver_tarefas_pendentes: "Ver tarefas pendentes",
  voce_esta_explorando_uma_demonstracao:
    "Você está explorando uma demonstração.",
  os_dados_sao_exemplos_e_ficam_neste_navegador:
    "Os dados são exemplos e ficam neste navegador.",
  usar_com_meus_clientes: "Usar com meus clientes",
  text_2: "☀",
  seu_negocio_em_boas_maos: "SEU NEGÓCIO EM BOAS MÃOS",
  um_bom_dia_para_crescer: "Um bom dia para crescer",
  text_3: ".",
  menos_coisas_na_cabeca_mais_tempo_para_quem_importa:
    "Menos coisas na cabeça. Mais tempo para quem importa.",
  cada_conversa_e_um_comeco: "CADA CONVERSA É UM COMEÇO",
  seu_proximo_cliente: "Seu próximo cliente",
  pode_estar_a_um_oi_de_distancia: "pode estar a um “oi” de distância.",
  tem_gente_esperando_por_voce_vamos_fazer_o_dia_acontece:
    "Tem gente esperando por você. Vamos fazer o dia acontecer?",
  vamos_conversar: "Vamos conversar",
  conhecer_alguem_novo: "Conhecer alguém novo",
  oi_quero_saber_mais: "Oi! Quero saber mais ✨",
  text_4: "✳",
  text_5: "✦",
  mais_perto_de_conquistar: "Mais perto de conquistar.",
  esperando: "esperando",
  responder_agora: "Responder agora",
  uma_boa_conversa_muda_o_dia: "Uma boa conversa muda o dia.",
  todo_mundo_respondido: "Todo mundo respondido!",
  abrir_conversas: "Abrir conversas",
  para_cuidar: "para cuidar",
  dar_o_proximo_passo: "Dar o próximo passo",
  pequenos_retornos_grandes_oportunidades:
    "Pequenos retornos, grandes oportunidades.",
  concluir: "Concluir ",
  dia_em_dia_voce_merece: "Dia em dia. Você merece!",
  ver_minha_agenda: "Ver minha agenda",
  ultimos_7_dias: "Últimos 7 dias",
  motivos_para_comemorar: "Motivos para comemorar",
  cada_conquista_conta_olha_as_suas: "Cada conquista conta. Olha as suas!",
  em_negocios_conquistados: "em negócios conquistados",
  clientes_conquistados: "clientes conquistados",
  acompanhar_resultados: "Acompanhar resultados",
  o_que_vamos_fazer_agora: "O que vamos fazer agora?",
  o_essencial_sempre_por_perto: "O essencial, sempre por perto.",
  adicionar_pessoa: "Adicionar pessoa",
  criar_um_negocio: "Criar um negócio",
  lembrar_de_algo: "Lembrar de algo",
  voce_cuida_dos_seus_clientes_a_gente_cuida_do_resto:
    "Você cuida dos seus clientes. A gente cuida do resto.",
  pessoas_nao_numeros: "Pessoas, não números.",
  filtrar_por_origem: "Filtrar por origem",
  importar_2: "Importar",
  exportar_pessoas: "Exportar pessoas",
  uma_oportunidade_em_cada_conversa: "Uma oportunidade em cada conversa.",
  telefone_2: "Telefone",
  como_chegou_2: "Como chegou",
  etiquetas_2: "Etiquetas",
  ultimo_contato: "Último contato",
  vamos_conhecer_melhor: "Vamos conhecer melhor",
  conversar_com: "Conversar com ",
  nenhuma_pessoa_encontrada: "Nenhuma pessoa encontrada",
  sua_primeira_pessoa_faz_toda_a_diferenca:
    "Sua primeira pessoa faz toda a diferença",
  tente_outro_nome_ou_telefone: "Tente outro nome ou telefone.",
  exemplo_cadastre_alguem_que_pediu_informacoes_sobre_seu:
    "Exemplo: cadastre alguém que pediu informações sobre seu negócio.",
  adicionar_minha_primeira_pessoa: "Adicionar minha primeira pessoa",
  de_um_primeiro_oi_a_uma_conquista: "De um primeiro oi a uma conquista.",
  novo_negocio: "Novo negócio",
  negocios_no_caminho: "negócios no caminho",
  em_oportunidades: "em oportunidades",
  arraste_um_cartao_ou_escolha_a_etapa: "Arraste um cartão ou escolha a etapa.",
  adicionar_em: "Adicionar em ",
  d_nesta_etapa: "d nesta etapa",
  conversar_sobre: "Conversar sobre ",
  etapa_de: "Etapa de ",
  um_espaco_para_a_proxima_oportunidade:
    "Um espaço para a próxima oportunidade.",
  nao_foi_desta_vez_2: "Não foi desta vez (",
  text_6: ")",
  text_7: "· ",
  boas_conversas_comecam_aqui: "Boas conversas começam aqui.",
  conversas_de_exemplo: "Conversas de exemplo",
  whatsapp_ainda_nao_conectado: "WhatsApp ainda não conectado",
  explore_a_caixa_e_teste_seus_rascunhos:
    "Explore a caixa e teste seus rascunhos.",
  as_respostas_sao_salvas_como_rascunho_nenhuma_mensagem_:
    "As respostas são salvas como rascunho. Nenhuma mensagem é enviada.",
  ver_conexao: "Ver conexão",
  buscar_conversa: "Buscar conversa",
  todas_as_conversas: "TODAS AS CONVERSAS ",
  comece_uma_boa_conversa: "Comece uma boa conversa",
  conversa_de_exemplo: "Conversa de exemplo",
  rascunhos_e_notas_internas: "Rascunhos e notas internas",
  ver_pessoa: "Ver pessoa",
  sua_historia_com: "Sua história com ",
  nota_interna: "Nota interna · ",
  rascunho: "Rascunho · ",
  uma_nova_conversa_comeca_aqui: "Uma nova conversa começa aqui",
  resposta: "Resposta",
  nota_interna_2: "Nota interna",
  usar_modelo: "Usar modelo",
  escrever_nota_interna: "Escrever nota interna",
  escrever_resposta: "Escrever resposta",
  uma_anotacao_so_para_sua_equipe: "Uma anotação só para sua equipe…",
  escreva_com_seu_jeito_uma_boa_conversa_aproxima:
    "Escreva com seu jeito. Uma boa conversa aproxima.",
  so_sua_equipe_pode_ver: "Só sua equipe pode ver",
  nenhum_envio_externo_ativado: "Nenhum envio externo ativado",
  salvar_nota: "Salvar nota",
  salvar_rascunho: "Salvar rascunho",
  quem_vai_ser_a_primeira_conversa: "Quem vai ser a primeira conversa?",
  espaco_na_agenda_leveza_na_cabeca: "Espaço na agenda. Leveza na cabeça.",
  seus_proximos_passos: "Seus próximos passos",
  pendentes: "pendentes",
  excluir: "Excluir ",
  tudo_feito_respira_e_comemora: "Tudo feito. Respira e comemora!",
  concluidos: "Concluídos (",
  reabrir: "Reabrir",
  seu_dia_cabe_aqui: "Seu dia cabe aqui.",
  uma_tarefa_de_cada_vez_um_cliente_mais_perto_voce_esta_:
    "Uma tarefa de cada vez. Um cliente mais perto. Você está no caminho certo.",
  planejar_meu_proximo_passo: "Planejar meu próximo passo",
  uma_maozinha_que_faz_diferenca: "Uma mãozinha que faz diferença.",
  criar_robo: "Criar robô",
  simples_assim_quando_acontecer_isto_espere_e_faca_aquil:
    "Simples assim: quando acontecer isto, espere e faça aquilo.",
  os_robos_criam_tarefas_a_fila_e_processada_a_cada_minut:
    "Os robôs criam tarefas. A fila é processada a cada minuto, mesmo quando você fecha o aplicativo.",
  sem_custo_de_envio: "Sem custo de envio",
  ligado: "Ligado",
  desligado: "Desligado",
  quando_uma_pessoa_nova_chegar_ajude_sua_equipe_a_dar_o_:
    "Quando uma pessoa nova chegar, ajude sua equipe a dar o primeiro passo.",
  quando_um_negocio_ficar_parado_lembre_sua_equipe_de_ret:
    "Quando um negócio ficar parado, lembre sua equipe de retomar a conversa.",
  uma_pessoa_chega: "Uma pessoa chega",
  um_negocio_fica_parado: "Um negócio fica parado",
  esperar: "Esperar ",
  horas: "horas",
  personalizar: "Personalizar",
  ativar: "Ativar ",
  voce_esta_no_comando_nenhum_robo_envia_mensagens_ou_con:
    "Você está no comando. Nenhum robô envia mensagens ou contrata serviços.",
  abra_a_porta_para_novos_clientes: "Abra a porta para novos clientes.",
  sua_pagina_de_captacao: "SUA PÁGINA DE CAPTAÇÃO",
  o_primeiro_oi_fica_mais_facil: "O primeiro oi fica mais fácil.",
  compartilhe_seu_link_no_instagram_nas_redes_ou_no_balca:
    "Compartilhe seu link no Instagram, nas redes ou no balcão. Quem preencher aparece na sua lista de pessoas.",
  convide_com_o_seu_jeito: "Convide com o seu jeito",
  link_da_pagina: "Link da página",
  copiar_link: "Copiar link",
  link_copiado: "Link copiado!",
  selecione_o_link_e_copie_para_compartilhar:
    "Selecione o link e copie para compartilhar.",
  salvar_pagina: "Salvar página",
  ativar_minha_pagina: "Ativar minha página",
  entre_na_sua_conta_para_ativar_uma_pagina_real:
    "Entre na sua conta para ativar uma página real.",
  pausar_pagina: "Pausar página",
  qr_code_da_pagina_de_captacao: "QR code da página de captação",
  do_mundo_real_para_uma_conversa: "Do mundo real para uma conversa.",
  coloque_seu_qr_no_balcao_ou_no_cartao_do_seu_negocio:
    "Coloque seu QR no balcão ou no cartão do seu negócio.",
  baixar_qr_code: "Baixar QR code",
  assim_seus_clientes_vao_ver: "ASSIM SEUS CLIENTES VÃO VER",
  quero_receber_um_contato_deste_negocio:
    "Quero receber um contato deste negócio.",
  abrir_minha_pagina: "Abrir minha página",
  seu_esforco_esta_virando_historia: "Seu esforço está virando história.",
  periodo_dos_resultados: "Período dos resultados",
  ultimos_30_dias: "Últimos 30 dias",
  ultimos_90_dias: "Últimos 90 dias",
  pessoas_chegaram: "Pessoas chegaram",
  comecaram_uma_conversa: "Começaram uma conversa",
  clientes_conquistados_2: "Clientes conquistados",
  em_negocios_conquistados_2: "Em negócios conquistados",
  neste_periodo: "Neste período",
  de_onde_vem_suas_pessoas: "De onde vêm suas pessoas?",
  insert: "INSERT",
  os_proximos_numeros_comecam_com_voce: "Os próximos números começam com você",
  seu_caminho_agora: "Seu caminho, agora",
  fotografia_dos_negocios_atuais_as_conquistas_acima_segu:
    "Fotografia dos negócios atuais. As conquistas acima seguem o período escolhido.",
  um_espaco_com_a_sua_cara: "Um espaço com a sua cara.",
  seu_negocio: "Seu negócio",
  nome_do_negocio: "Nome do negócio",
  seu_nicho: "Seu nicho",
  novo_exemplo_preparado_para_voce: "Novo exemplo preparado para você.",
  salvar_alteracoes: "Salvar alterações",
  animacoes_e_pequenos_momentos: "Animações e pequenos momentos",
  um_toque_de_leveza_no_dia_a_dia: "Um toque de leveza no dia a dia.",
  animacoes: "Animações",
  conexoes_e_seguranca: "Conexões e segurança",
  whatsapp_oficial: "WhatsApp oficial",
  nao_conectado_nenhum_envio_cobrado: "Não conectado · nenhum envio cobrado",
  a_conexao_exige_credenciais_da_whatsapp_business_platfo:
    "A conexão exige credenciais da WhatsApp Business Platform e pode gerar cobrança por mensagens. Esta versão mantém os envios desativados.",
  assistencia_com_ia: "Assistência com IA",
  modelos_prontos_sem_chamadas_pagas: "Modelos prontos · sem chamadas pagas",
  conta_real_protegida_por_dois_fatores:
    "Conta real protegida por dois fatores",
  verificacao_em_dois_fatores_ativa: "Verificação em dois fatores ativa",
  crie_sua_conta_para_guardar_seus_clientes:
    "Crie sua conta para guardar seus clientes.",
  seus_dados_sao_isolados_por_negocio: "Seus dados são isolados por negócio.",
  entrar_na_minha_conta: "Entrar na minha conta",
  sair_da_conta: "Sair da conta",
  seus_dados_seu_controle: "Seus dados, seu controle",
  itens_excluidos_podem_ser_restaurados_por_ate_30_dias:
    "Itens excluídos podem ser restaurados por até 30 dias.",
  abrir_lixeira: "Abrir lixeira",
  demonstracao_reiniciada: "Demonstração reiniciada.",
  recomecar_demonstracao: "Recomeçar demonstração",
  exemplos_removidos_voce_pode_recomecar_a_demonstracao_n:
    "Exemplos removidos. Você pode recomeçar a demonstração nas configurações.",
  limpar_exemplos: "Limpar exemplos",
  mudou_de_ideia_tudo_bem: "Mudou de ideia? Tudo bem.",
  item: "Item",
  excluido_em: "Excluído em ",
  restaurar: "Restaurar",
  nada_por_aqui: "Nada por aqui",
  feito_para_aproximar: "Feito para aproximar.",
  demonstracao_local: "Demonstração local",
  conectado_ao_seu_espaco: "Conectado ao seu espaço",
  desfazer: "Desfazer",
  veja_o_que_seu_robo_vai_fazer: "Veja o que seu robô vai fazer",
  para_cada_nova_pessoa_cadastrada_a_partir_da_ativacao:
    "Para cada nova pessoa cadastrada a partir da ativação",
  para_cada_negocio_parado_alem_do_tempo_escolhido:
    "Para cada negócio parado além do tempo escolhido",
  criar_uma_tarefa_apos: ", criar uma tarefa após ",
  horas_2: "horas.",
  exemplo_com_sua_conta_a_proxima_pessoa_recebera_um_lemb:
    "Exemplo com sua conta: a próxima pessoa receberá um lembrete interno para a equipe. Nenhuma pessoa existente será contatada.",
  nenhuma_mensagem_sera_enviada_os_lembretes_sao_processa:
    "Nenhuma mensagem será enviada. Os lembretes são processados em segundo plano, a cada minuto.",
  agora_nao: "Agora não",
  ativar_robo: "Ativar robô",
  cada_pessoa_tem_uma_historia: "Cada pessoa tem uma história",
  anote_aqui_o_que_torna_esse_cliente_especial:
    "Anote aqui o que torna esse cliente especial.",
  negocios: "negócios",
  conquistados: "conquistados",
  autorizacao_registrada: "Autorização registrada",
  sem_autorizacao_para_disparos: "Sem autorização para disparos",
  a_historia_ate_aqui: "A história até aqui",
  nota_da_equipe: "Nota da equipe",
  mensagem_recebida: "Mensagem recebida",
  rascunho_preparado: "Rascunho preparado",
  concluida: "Concluída",
  planejada: "Planejada",
  mover_para_lixeira: "Mover para lixeira",
  abrir_conversa: "Abrir conversa",
  seu_negocio_mais_perto: "Seu negócio, mais perto",
  comece_pela_tela_hoje_ela_mostra_quem_espera_uma_respos:
    "Comece pela tela Hoje. Ela mostra quem espera uma resposta, seus próximos passos e o que você já conquistou.",
  adicione_uma_pessoa_com_nome_e_telefone:
    "Adicione uma pessoa com nome e telefone.",
  crie_um_negocio_e_acompanhe_cada_etapa:
    "Crie um negócio e acompanhe cada etapa.",
  prepare_respostas_e_anote_o_que_combinaram:
    "Prepare respostas e anote o que combinaram.",
  use_a_agenda_e_os_robos_para_lembrar_de_voltar:
    "Use a agenda e os robôs para lembrar de voltar.",
  vamos_comecar: "Vamos começar",
} as const;
