// Vocabulário de navegação e ações compartilhadas. Conteúdo de nicho vive em data/niches.ts.
export const pt = {
  brand: "atraction",
  today: "Hoje",
  contacts: "Pessoas",
  deals: "Caminho do cliente",
  messages: "Conversas",
  automations: "Robôs",
  capture: "Atrair clientes",
  results: "Resultados",
  calendar: "Agenda",
  settings: "Configurações",
  trash: "Lixeira",
  newContact: "Nova pessoa",
  newDeal: "Novo negócio",
  newTask: "Nova tarefa",
  save: "Salvar",
  cancel: "Cancelar",
  undo: "Desfazer",
  search: "Buscar pessoas, telefone ou etiquetas...",
  example: "Demonstração",
  loading: "Preparando seu espaço…",
  error: "Não foi possível salvar. Confira sua conexão e tente novamente.",
  duplicate:
    "Esse telefone já está cadastrado. Busque a pessoa para continuar.",
  saved: "Pronto, alteração salva.",
  deleted: "Movido para a lixeira por 30 dias.",
  empty: "O próximo capítulo começa aqui.",
  login: "Entrar na minha conta",
  logout: "Sair da conta",
};
